### ISSUE TITLE
[Refactor] firebase周りの処理リファクタ

### ISSUE THREAD

**Issue by xyytgae** [xyytgae/my-molkky#116]
# 概要

- firebase周りの変数名、関数名、共通化できる処理は共通化等のリファクタ
  - apis/waitingRoom.ts
  - apis/waitingUser.ts
  - composables/useWaitingRoom.ts
  - composables/useWaitingUsers.ts

# Todo

- firebase周りの変数名、関数名、共通化できる処理は共通化等のリファクタ
  - [ ] apis/waitingRoom.ts
  - [ ] apis/waitingUser.ts
  - [ ] composables/useWaitingRoom.ts
  - [ ] composables/useWaitingUsers.ts

# 該当ページ

- 

# 参考

-
