### ISSUE TITLE
[Feature] v-appをlayouts/default.vueに移動させる

### ISSUE THREAD

**Issue by xyytgae** [xyytgae/my-molkky#128]
# 概要

- `<v-app>`を`layouts/default.vue`に移動させる
- ビューは`<v-main>`に配置する
- ヘッダーやフッターを`<v-main>`外に配置する

# Todo

- [x] `<v-app>`を`layouts/default.vue`に移動させる
- [x] ビューは`<v-main>`に配置する
- [x] ヘッダーやフッターを`<v-main>`外に配置する

# 該当ページ

- 

# 参考

- https://v2.vuetifyjs.com/ja/components/application/#section-30c730d530a930eb30c8306e30a230d730ea30b130fc30b730e730f330de30fc30af30a230c330d7
